{% set name = "pytest-icdiff" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13aede616202e57fcc882568b64589002ef85438046f012ac30a8d959dac8b75

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - icdiff
    - pprintpp
    - pytest
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_icdiff

about:
  home: https://github.com/hjwp/pytest-icdiff
  license: Unlicense
  license_family: OTHER
  license_file: LICENSE
  summary: use icdiff for better error messages in pytest assertions

extra:
  recipe-maintainers:
    - nicoddemus
